### ISSUE TITLE
NegTokenInit.ContextFlags cannot be parsed

### ISSUE THREAD

**Issue by bedrin** [bedrin/kerb4j#1]
ContextFlags is parsed as Asn1Flags while it should be Asn1BitString

```
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.apache.kerby.asn1.type.Asn1Flags.value2Flags(Asn1Flags.java:118)
	at org.apache.kerby.asn1.type.Asn1Flags.setValue(Asn1Flags.java:63)
	at org.apache.kerby.asn1.type.Asn1Flags.setValue(Asn1Flags.java:31)
	at org.apache.kerby.asn1.type.Asn1BitString.toValue(Asn1BitString.java:84)
	at org.apache.kerby.asn1.type.Asn1Flags.toValue(Asn1Flags.java:124)
	at org.apache.kerby.asn1.type.Asn1Simple.decodeBody(Asn1Simple.java:100)
	at org.apache.kerby.asn1.type.Asn1Encodeable.decode(Asn1Encodeable.java:224)
	at org.apache.kerby.asn1.type.Asn1Encodeable.taggedDecode(Asn1Encodeable.java:299)
	at org.apache.kerby.asn1.Asn1Binder.bindWithTagging(Asn1Binder.java:49)
	at org.apache.kerby.asn1.type.Asn1CollectionType.attemptBinding(Asn1CollectionType.java:127)
	at org.apache.kerby.asn1.type.Asn1CollectionType.decodeBody(Asn1CollectionType.java:111)
	at org.apache.kerby.asn1.type.Asn1Encodeable.decode(Asn1Encodeable.java:224)
	at com.kerb4j.spnego.SpnegoInitToken.<init>(SpnegoInitToken.java:58)
```

**Comment by bedrin** [comment]
Fixed in 0.0.2-SNAPSHOT
